name: Build
description: Build postgres image
inputs:
  version:
    description: version
    required: true
  tags:
    description: image tags
    required: true
  platform:
    description: os/arch
    required: false
    default: linux/amd64
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      POSTGRES_VER: ${{ inputs.version }}
      TAGS: ${{ inputs.tags }}
      PLATFORM: ${{ inputs.platform }}
    run: |
      set -e
      make buildx-build-amd64
      make test
      make buildx-build
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
