name: push
description: combine multi-arch image and push
inputs:
  version:
    description: version
    required: true
  latest:
    description: optional floating alias
    required: false
  latest_major:
    description: if tag latest major version
    required: false
  tag_suffix:
    description: suffix appended to major and minor tags
    required: false
runs:
  using: "composite"
  steps:
    - name: Build image
      env:
        POSTGRES_VER: ${{ inputs.version }}
        LATEST_ALIAS: ${{ inputs.latest }}
        LATEST_MAJOR: ${{ inputs.latest_major }}
        TAG_SUFFIX: ${{ inputs.tag_suffix }}
      run: |
        . $GITHUB_ACTION_PATH/release.sh
      shell: bash
      working-directory: ${{ inputs.workdir }}
